development:
  adapter: postgresql
  database: takearide_development
  host: localhost
  username: takearide
  password: takearide
  encoding: utf8
  min_messages: warning

test:
  adapter: postgresql
  database: takearide_test
  host: localhost
  username: takearide
  password: takearide
  encoding: utf8
  min_messages: warning

production:
  adapter: postgresql
  database: takearide_production
  host: localhost
  username: takearide
  password: takearide
  encoding: utf8
  min_messages: warning
